---
bichon_version: "0.2.0"
bichon_port: 15630
bichon_sys_user: bichon
bichon_sys_group: bichon
bichon_install_dir: /opt/bichon
bichon_root_dir: /opt/bichon/data
bichon_index_dir: /opt/bichon/data/index
bichon_data_dir: /opt/bichon/data/store
bichon_log_level: info

bichon_subdomain: bichon
bichon_domain: "{{ bichon_subdomain }}.{{ primary_domain }}"

bichon_release_url: "https://github.com/rustmailer/bichon/releases/download/v{{ bichon_version }}/bichon-x86_64-unknown-linux-gnu.tar.gz"
