admin_user_email = ""
admin_user_name = ""

baikal_admin_password = ""
baikal_subdomain = ""

blocky_subdomain = ""

booklore_admin_password = ""
booklore_admin_user = ""
booklore_db_password = ""
booklore_subdomain = ""

cloudflare_dns_api_token = ""

colporteur_feeds_password = ""
colporteur_subdomain = ""

domain = ""

freshrss_subdomain = ""

navidrome_subdomain = ""

openclaw_claude_ai_session_key = ""
openclaw_claude_web_cookie = ""
openclaw_claude_web_session_key = ""
openclaw_gateway_token = ""

paperless_admin_password = ""
paperless_admin_user = ""
paperless_db_password = ""
paperless_secret_key = ""

ssh_port = 22022

tailscale_api_key = ""
tailscale_authkey = ""

webdav_password = ""
webdav_subdomain = ""

yourls_admin_password = ""
yourls_admin_user = ""
yourls_api_signature = ""
yourls_cookiekey = ""
yourls_db_password = ""
yourls_subdomain = ""

zone_id = ""
