[tasks.build]
alias = "b"
description = "Build"
run = "cargo build --release"
silent = true

[tasks.auberge]
alias = "a"
depends = "build"
description = "Run auberge"
raw = true
run = "{{ vars.auberge_cli }}"
silent = true

[tasks.fmt]
alias = "f"
description = "Format"
run = "dprint fmt -c .dprint.jsonc"
silent = true

[tasks.lint-ansible]
run = "ansible-lint"
dir = "ansible"
quiet = true

[tasks.lint-rust]
run = "cargo clippy"
quiet = true

[tasks.lint]
alias = "l"
depends = "lint-*"
quiet = true

[tasks.test]
alias = "t"
run = "cargo nextest run"
quiet = true

[tools]
caddy = "latest"
"cargo:convco" = "latest"
dasel = "latest"
dprint = "latest"
hk = "latest"
pipx = "latest"
pkl = "latest"
ansible = "latest"
"pipx:ansible-dev-tools" = "latest"
"pipx:ansible-lint" = "latest"
rust = "latest"
"cargo:cargo-nextest" = "latest"
"npm:docsify-cli" = "latest"

[vars]
auberge_cli = "cargo run --release"
