blocky_domain: "{{ blocky_subdomain }}.{{ domain }}"
blocky_install_path: /usr/local/bin/blocky
blocky_config_path: /etc/blocky

blocky_target_arch: "Linux_x86_64"
blocky_binary_file_extension: "tar.gz"
blocky_archive_name: "blocky_v{{ blocky_version }}_{{ blocky_target_arch }}.{{ blocky_binary_file_extension }}"
blocky_archive_url: "https://github.com/0xERR0R/blocky/releases/download/v{{ blocky_version }}/{{ blocky_archive_name }}"
blocky_checksums_url: "https://github.com/0xERR0R/blocky/releases/download/v{{ blocky_version }}/blocky_checksums.txt"

# renovate: datasource=github-releases depName=go-acme/lego extractVersion=^v(?<version>.+)$
blocky_lego_version: "4.23.1"
blocky_lego_url: "https://github.com/go-acme/lego/releases/download/v{{ blocky_lego_version }}/lego_v{{ blocky_lego_version }}_linux_amd64.tar.gz"
blocky_lego_sha256: "1fd60b1fd59c239bed22719a5de402cb745d1f933540cb1ec196e2c03e6e8882"

blocky_dot_port: 853

blocky_cert_dir: "{{ blocky_config_path }}/certificates"
blocky_cert_file: "{{ blocky_cert_dir }}/{{ blocky_domain }}.crt"
blocky_key_file: "{{ blocky_cert_dir }}/{{ blocky_domain }}.key"

blocky_letsencrypt_email: "{{ admin_user_email }}"

blocky_tailscale_bound_domains: []
