- name: Restart navidrome
  ansible.builtin.systemd_service:
    name: navidrome
    state: restarted
    daemon_reload: true

- name: Restart caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
