vdirsyncer_install_dir: /opt/vdirsyncer
vdirsyncer_status_dir: /var/lib/vdirsyncer/status
vdirsyncer_config_dir: /etc/vdirsyncer
vdirsyncer_sys_user: vdirsyncer
vdirsyncer_sys_group: vdirsyncer
vdirsyncer_sync_interval: 2min
vdirsyncer_baikal_calendar_url: "https://{{ baikal_subdomain }}.{{ domain }}/cal.php/calendars/{{ admin_user_name }}/"
vdirsyncer_icloud_calendar_id: "{{ vdirsyncer_icloud_url | regex_replace('/$', '') | urlsplit('path') | basename }}"
