required_keys:
  - admin_user_email
  - baikal_admin_password
  - baikal_busy_feed_token
  - baikal_subdomain
subdomain: baikal
version:
  value: "0.12.1"
  datasource: github-releases
  depName: "sabre-io/Baikal"
backup:
  paths: [/opt/baikal/Specific]
  owner: [baikal, baikal]
units:
  - baikal-birthday-sync
  - baikal-birthday-sync.timer
  - baikal-busy-sync
  - baikal-busy-sync.timer
