required_keys: []
tailnet_only: true
subdomain: bichon
version:
  value: "2.0.2"
  datasource: github-releases
  depName: "rustmailer/bichon"
backup:
  systemd_services: [bichon]
  paths: [/var/lib/bichon-archive]
  owner: [bichon, bichon]
