required_keys: []
subdomain: blocky
version:
  value: "0.34.0"
  datasource: github-releases
  depName: "0xERR0R/blocky"
  extractVersion: "^v(?<version>.+)$"
units: [blocky, lego-renew, lego-renew.timer]
