required_keys:
  - colporteur_feeds_password
  - colporteur_subdomain
subdomain: colporteur
version:
  value: "0.6.1"
  datasource: github-releases
  depName: "sripwoud/colporteur"
  extractVersion: "^v(?<version>.+)$"
units: [colporteur, colporteur.timer]
