required_keys: []
subdomain: colporteur
version:
  value: "0.6.0"
  datasource: github-releases
  depName: "sripwoud/colporteur"
  extractVersion: "^v(?<version>.+)$"
units: [colporteur, colporteur.timer]
