required_keys: []
subdomain: freshrss
version:
  value: "1.29.1"
  datasource: github-releases
  depName: "FreshRSS/FreshRSS"
backup:
  systemd_services: [freshrss]
  paths: [/var/lib/freshrss, /opt/freshrss/data]
  owner: [freshrss, freshrss]
units: [freshrss, freshrss-update, freshrss-update.timer]
