required_keys:
  - cloudflare_dns_api_token
  - domain
  - gokapi_admin_password
  - gokapi_admin_user
  - gokapi_subdomain
subdomain: share
version:
  value: "2.2.4"
  datasource: github-releases
  depName: "Forceu/Gokapi"
  extractVersion: "^v(?<version>.+)$"
backup:
  systemd_services: [gokapi]
  paths: [/var/lib/gokapi]
  owner: [gokapi, gokapi]
units: [gokapi]
