required_keys:
  - domain
  - cloudflare_dns_api_token
  - immich_b2_application_key
  - immich_b2_key_id
  - immich_db_password
  - immich_restic_password
  - immich_restic_repository
  - immich_subdomain
subdomain: photos
version:
  value: "3.1.0"
  datasource: github-releases
  depName: "immich-app/immich"
  extractVersion: "^v(?<version>.+)$"
units: [immich, immich-backup, immich-backup.timer]
