required_keys:
  - yourls_admin_password
  - yourls_admin_user
  - yourls_cookiekey
  - yourls_db_password
  - yourls_subdomain
subdomain: yourls
version:
  value: "1.10.4"
  datasource: github-releases
  depName: "YOURLS/YOURLS"
backup:
  paths: [/var/www/yourls]
  owner: [www-data, www-data]
  db:
    name: yourls
    engine: mariadb
    dump_path: /tmp/yourls_db.dump
