---
ansible_user_ssh_public_key_file: "{{ ssh_identities_dir }}/ansible.pub"
ansible_user_admin_name: "{{ admin_user_name }}"
ansible_user_admin_ssh_public_key_file: "{{ ssh_identities_dir }}/{{ admin_user_name }}.pub"
ansible_user_shell: /bin/bash
ansible_user_admin_shell: /bin/bash
