---
all:
  children:
    vps:
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: "{{ ssh_identities_dir }}/ansible"
        admin_ssh_private_key_file: "{{ ssh_identities_dir }}/{{ admin_user_name }}"
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
        ansible_ssh_common_args: >-
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o UserKnownHostsFile={{ lookup('env', 'HOME') }}/.ssh/known_hosts
          -o StrictHostKeyChecking=accept-new
          -o IdentitiesOnly=yes
