radio_domain: "{{ radio_subdomain }}.{{ domain }}"
radio_icecast_port: 8005
radio_icecast_user: icecast2
radio_icecast_group: icecast
radio_liquidsoap_user: liquidsoap
radio_liquidsoap_group: liquidsoap
radio_config_dir: /etc/liquidsoap
radio_stations_dir: /srv/music/Stations
radio_music_group: navidrome
radio_source_password_file: /etc/icecast2/source_password
radio_bitrate: 128
radio_max_clients: 32
radio_max_sources: 8
