#!/bin/sh
# mise description="Run selected playbook on selected host"
set -eu

run_bootstrap() {
  host="$1"
  playbook="$2"

  echo "Running bootstrap playbook on $host..."
  ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.yml "$playbook" \
    --ask-pass \
    --limit "$host" \
    -e "ansible_ssh_common_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no'"
}

run_standard() {
  host="$1"
  playbook="$2"

  echo "Running $playbook on $host..."
  ansible-playbook -i inventory.yml "$playbook" \
    --ask-vault-pass \
    --limit "$host" \
    -e "@group_vars/all/secrets.vault"
}

main() {
  host=$(mise run select-host)
  playbook=$(mise run select-playbook)

  case "$playbook" in
  *bootstrap.yml)
    run_bootstrap "$host" "$playbook"
    ;;
  *)
    run_standard "$host" "$playbook"
    ;;
  esac
}

main
