---
caddy_l4_version: "v0.1.0"
caddy_cloudflare_plugin_version: "v0.2.4"

caddy_binary: /usr/local/bin/caddy
caddy_build_id_file: /usr/local/bin/.caddy-build-id
caddy_build_id: "l4-{{ caddy_l4_version }}-cf-{{ caddy_cloudflare_plugin_version }}"
